---
apiVersion: v1
kind: Service
metadata:
  name: "page-404"
  namespace: static-sites
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: "page-404"
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "page-404"
  namespace: static-sites
spec:
  selector:
    matchLabels:
      app: "page-404"
  replicas: 1
  template:
    metadata:
      labels:
        app: "page-404"
    spec:
      containers:
      - name: app
        image: ghcr.io/tlwr/page-404:@tag
        ports:
        - containerPort: 8080
...
