---
apiVersion: v1
kind: Service
metadata:
  name: stats-tobys-cloud
  namespace: static-sites
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: stats-tobys-cloud
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-tobys-cloud
  namespace: static-sites
spec:
  selector:
    matchLabels:
      app: stats-tobys-cloud
  replicas: 2
  template:
    metadata:
      labels:
        app: stats-tobys-cloud
    spec:
      containers:
      - name: nginx
        image: ghcr.io/tlwr/stats.tobys.cloud:@tag
        command: [/app/server]
        args:
          - -prometheus-url
          - prometheus-operated.prometheus-system.svc.cluster.local
        ports:
        - containerPort: 8080
...

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: stats-tobys-cloud
  namespace: static-sites
spec:
  secretName: stats-tobys-cloud-tls
  dnsNames:
  - stats.tobys.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
...

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stats-tobys-cloud
  namespace: static-sites
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - stats.tobys.cloud
      secretName: stats-tobys-cloud-tls
  rules:
  - host: stats.tobys.cloud
    http:
      paths:
      - backend:
          serviceName: stats-tobys-cloud
          servicePort: 8080
...
