---
apiVersion: v1
kind: Service
metadata:
  name: todos-tobys-cloud
  namespace: static-sites
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: todos-tobys-cloud
...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-tobys-cloud
  namespace: static-sites
spec:
  selector:
    matchLabels:
      app: todos-tobys-cloud
  replicas: 1
  template:
    metadata:
      labels:
        app: todos-tobys-cloud
    spec:
      containers:
      - name: nginx
        image: ghcr.io/tlwr/todo-aggregator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ['todo-aggregator']
        args: ['-github-username', 'tlwr']
...

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: todos-tobys-cloud
  namespace: static-sites
spec:
  secretName: todos-tobys-cloud-tls
  dnsNames:
  - todos.tobys.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
...

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-tobys-cloud
  namespace: static-sites
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - todos.tobys.cloud
      secretName: todos-tobys-cloud-tls
  rules:
  - host: todos.tobys.cloud
    http:
      paths:
      - backend:
          serviceName: todos-tobys-cloud
          servicePort: 8080
...
